// TODO 要處理 Unary 的狀況，或是說可以先無視

<Program> ::= <Block>

<Block> ::= int main ( ) <CompoundStatement>

<CompoundStatement> ::= { <StatementList> }

<StatementList> ::= <Statement> <StatementList> | epsilon

<Statement> ::= <AssignmentStatement> ;
              | <CompoundStatement>
              | <DeclareStatement> ;
              | <IfStatement>
              | <WhileStatement>
              | epsilon

<AssignmentStatement> ::= <Identifier> = <Expression>

<InitDeclarator> ::= <Identifier> [ = <Expression> ]

<DeclareStatement> ::= <Type> <InitDeclarator> { , <InitDeclarator> }

<IfStatement> ::= if ( <Expression> ) <CompoundStatement> [ else <CompoundStatement> ]

<WhileStatement> ::= while ( <Expression> ) <CompoundStatement>

<Expression> ::= <ArithmeticExpression> <RelationalPrime>

<RelationalPrime> ::= < <ArithmeticExpression> <RelationalPrime>
                    | <= <ArithmeticExpression> <RelationalPrime>
                    | > <ArithmeticExpression> <RelationalPrime>
                    | >= <ArithmeticExpression> <RelationalPrime>
                    | == <ArithmeticExpression> <RelationalPrime>
                    | != <ArithmeticExpression> <RelationalPrime>
                    | epsilon

<ArithmeticExpression> := <Term> <ArithmeticPrime>

<ArithmeticPrime> ::= + <Term> <ArithmeticPrime>
                    | - <Term> <ArithmeticPrime>
                    | epsilon

<Term> ::= <Factor> <TermPrime>

<TermPrime> ::= * <Factor> <TermPrime>
              | / <Factor> <TermPrime>
              | epsilon

<Factor> ::= <Identifier> | <Number> | ( <Expression> )

<Identifier> ::= <Alpha> { <Alpha> | <Digit> } // TODO : 修改一下這邊的 production，不要用 EBNF 的 '{'

<Number> ::= <Digit> { <Digit> }                    

<Type> ::= int | char

<Alpha> ::= A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z

<Digit> ::= 0|1|2|3|4|5|6|7|8|9

