<Program> ::= <ProgramHead> <Block>.

<ProgramHead> ::= PROGRAM <Identifier>;

<Block> ::= [<ConstDeclaration>] [<VarDeclaration>] [<ProcDeclaration>] <CompoundStatement>

<ConstDeclaration> ::= CONST <Identifier> = <String> {,<Identifier>=<String>};        

<VarDeclaration> ::= VAR <IdentifierList> ;                   

<ProcDeclaration> ::= {PROCEDURE <Identifier>;<Block>;} 

<Statement> ::= [<AssignmentStatement> | <CallStatement> | <CompoundStatement> | <IfStatement> | <WhileStatement>]  |  <ReadStatement> | <WriteStatement>            

<AssignmentStatement> ::= <Identifier> := <Expression>                  

<CallStatement> ::= CALL <Identifier>            

<CompoundStatement> ::= BEGIN <Statement>{;<Statement>} END           

<IfStatement> ::= IF <Condition> THEN <Statement>               

<WhileStatement> ::= WHILE <Condition> DO <Statement> 

<ReadStatement> ::= READ ( <IdentifierList> )    

<WriteStatement> ::= WRITE ( <IdentifierList> )

<IdentifierList> ::= <Identifier> { , <Identifier> } 

<Condition> ::= <Expression> \<|<=|=|<>|>|>=\ <Expression>                 

<Expression> ::= [+|-] <Term> { \+|-\ <Term> }        

<Term> :: = <Factor> { \ *|/ \ <Factor> }             

<Factor> ::= <Identifier>|<Number>| (<Expression>)                      

<Identifier> ::= <Alpha> { <Alpha> | <Digit> }        

<Number> ::= <Digit> { <Digit> }                    

<Alpha> ::= A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z

<Digit> ::= 0|1|2|3|4|5|6|7|8|9                  

<String> ::= " 任何非雙引號的字元集合 " 